apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: new-accelerator-dy
spec:
  git:
    url: https://github.com/ydaoqi/new-accelerator-dy.git
    ref:
      branch: main
